### ISSUE TITLE
producturl dont work

### ISSUE THREAD

**Issue by kiahmed** [agaboduarte/AliExpressScraper#2]
**wondering if you could support it? ProdutUrl like this gives a null error**

D:\AliExpressScraper\AliScraperConsole\bin\Release>alishop -ProductUrl="https://www.aliexpress.com/item/1Pcs-Pet-Toys-LED-Laser-Pointer-Light-Cat-and-Dog-Laser-Projection-Toy-Color-Randomly-Free/32628151906.html?spm=2114.search0104.3.57.752f3c06yU7t8p&ws_ab_test=searchweb0_0,searchweb201602_2_10152_10151_10065_10344_10068_10130_10324_10342_10547_10325_10343_10546_10340_10548_10341_10545_10084_10083_10618_10307_5711211_10313_10059_10534_100031_10103_10627_10626_10624_10623_10622_10621_5722412_10620_10810_5711313,searchweb201603_2,ppcSwitch_2&algo_expid=65c8be8b-7cad-458c-8187-23395344d8fd-7&algo_pvid=65c8be8b-7cad-458c-8187-23395344d8fd&transAbTest=ae803_3&priceBeautifyAB=0"

 Assembly

  Title                    AliScraperConsole
  Company
  Copyright                Copyright c 2015
  Trademark
  Description              Ali Express Web Scraper
  Version                  1.0.0.0

 AliGetProduct

null

**Comment by agabopinho** [comment]
some things on the products page have been updated, to get around this needs constant updates.

https://github.com/agaboduarte/AliExpressScraper/commit/7d5e8f6df25c16101da4a4e72b8301899249a346
